config/routes.rb
Rails.application.routes.draw do
  # root to: 'samples#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'
  root to: 'posts#index'
  resources :posts do
    resources :comments, module: :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_post_id  (post_id)
#  index_comments_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (post_id => posts.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, length: { maximum: 1000 }
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
  validates :body, presence: true
  validates :images, presence: true,
                     blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..(5.megabytes) }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :bigint           not null, primary key
#  crypted_password :string(255)
#  email            :string(255)      not null
#  salt             :string(255)
#  username         :string(255)      not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_users_on_email     (email) UNIQUE
#  index_users_on_username  (username) UNIQUE
#
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  def owner?(object)
    object.user_id == id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  add_flash_types :primary, :success, :warning, :danger
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < ApplicationController
  before_action :require_login

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save
  end

  def edit
    @comment = current_user.comments.find(params[:id])
  end

  def update
    @comment = current_user.comments.find(params[:id])
    @comment.update(comment_params)
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
  end

  def show
    @comment = current_user.comments.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def index
    @pagy, @posts = pagy(Post.with_attached_images.includes(:user).order(created_at: :desc))
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post), success: '投稿しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), success: '投稿を更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path, success: '投稿を削除しました', status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:body, images: [])
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  def index; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new; end

  def create
    user = login(params[:email], params[:password])

    if user
      redirect_back_or_to '/', success: 'ログインしました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to login_path, success: 'ログアウトしました', status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to '/', success: 'ユーザー登録が完了しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/_header.html.erb
<!-- Navbar -->
<nav id="header" class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    <%= link_to root_path, class: 'navbar-brand me-2' do %>
      <%= image_tag 'logo.png', height: 30 %>
    <% end %>

    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to '投稿一覧', posts_path, class: 'nav-link' %>
        </li>
      </ul>
      <!-- Left links -->

      <div class="d-flex align-items-center">
        <% unless logged_in? %>
          <%= link_to 'ログイン', login_path, class: 'btn btn-link px-3 me-2' %>
          <%= link_to 'サインアップ', signup_path, class: 'btn btn-primary me-3' %>
        <% end %>

        <% if logged_in? %>
          <%= link_to new_post_path, class: 'btn btn-primary btn-sm me-3' do %>
            <i class="fas fa-camera me-2"></i>
            投稿
          <% end %>
          <!-- Avatar -->
          <div id="header-avatar-dropdown" class="dropdown">
            <a
              class="dropdown-toggle d-flex align-items-center hidden-arrow"
              href="#"
              id="navbarDropdownMenuAvatar"
              role="button"
              data-mdb-toggle="dropdown"
              aria-expanded="false">
              <img
                src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
                class="rounded-circle"
                height="25"
                alt="Black and White Portrait of a Man"
                loading="lazy">
            </a>
            <ul
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="navbarDropdownMenuAvatar">
              <li>
                <a class="dropdown-item" href="#">My profile</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Settings</a>
              </li>
              <li>
                <%= link_to 'ログアウト',
                            logout_path,
                            class: 'dropdown-item',
                            data: { turbo_method: :delete, turbo_confirm: 'ログアウトします' } %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstaCloneVer7</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Font Awesome -->
  <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet">
  <!-- Google Fonts -->
  <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet">
  <!-- MDB -->
  <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.11.0/mdb.min.css"
      rel="stylesheet">

  <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render 'layouts/header' %>
<%= render 'shared/flash_messages' %>
<%= yield %>

</body>
</html>

app/views/posts/_carousel_images.html.erb
<div class="bg-image hover-overlay ripple post-carousel-wrapper" data-mdb-ripple-color="light">
  <% carousel_indicator_id = dom_id(post, 'carouselIndicator') %>
  <div id="<%= carousel_indicator_id %>" class="carousel slide" data-mdb-ride="carousel" data-mdb-interval="false">
    <div class="carousel-indicators">
      <% post.images.size.times do |n| %>
        <button
          type="button"
          data-mdb-target="#<%= carousel_indicator_id %>"
          data-mdb-slide-to="<%= n.to_s %>"
          class="<%= 'active' if n.zero? %>"></button>
      <% end %>
    </div>
    <div class="carousel-inner">
      <% post.images.each_with_index do |image, index| %>
        <div class="carousel-item <%= 'active' if index.zero? %>">
          <%= image_tag image, class: 'd-block w-100' %>
        </div>
      <% end %>
    </div>
    <% if post.images.size > 1 %>
      <button class="carousel-control-prev" type="button" data-mdb-target="#<%= carousel_indicator_id %>" data-mdb-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-mdb-target="#<%= carousel_indicator_id %>" data-mdb-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    <% end %>
  </div>
  <%= link_to post_path(post) do %>
    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
  <%= render 'shared/error_messages', object: post %>
  <div class="mb-4">
    <%= f.label :body, class: 'form-label' %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="mb-4">
    <% if post.new_record? %>
      <%= f.label :images, class: 'form-label' %>
      <%= f.file_field :images, class: 'form-control', multiple: true, accept: 'image/*' %>
    <% end %>
    <% if post.persisted? %>
      <div class="d-flex align-items-center mt-3">
        <% post.images.each do |image| %>
          <%= image_tag image, width: '100px' %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id(post) %>" class="card mb-5 post-item">
  <%= render 'carousel_images', post: %>
  <div class="card-body">
    <p class="card-text"><%= post.body.truncate(50) %></p>
    <div class="d-flex justify-content-end mb-1">
      <i class="far fa-heart"></i>
    </div>
    <div class="d-flex justify-content-end">
      <span class="text-muted small"><%= l post.created_at, format: :long %></span>
    </div>
  </div>
  <div class="card-footer">

    <div class="d-flex align-items-center gap-3">
      <%= image_tag 'http://placehold.jp/40x40.png',
                    class: 'rounded-circle',
                    width: 40,
                    height: 40 %>
      <span><%= post.user.username %></span>
    </div>
  </div>
</div>

app/views/posts/comments/_comment.html.erb
<%= turbo_frame_tag dom_id comment do %>
  <div class="d-flex gap-3">
    <%= image_tag 'http://placehold.jp/40x40.png',
                  class: 'rounded-circle',
                  width: 40,
                  height: 40 %>
    <div class="w-100">
      <span class="font-weight-bold"><%= comment.user.username %></span>
    <%= simple_format(comment.body) %>
    <p class="card-text text-end">
      <small class="text-end"><%= l comment.created_at, format: :long %></small>
    </p>
    <% if current_user && current_user.owner?(comment) %>
      <div class="text-end">
        <span class="me-2">
          <%= link_to edit_post_comment_path(comment.post, comment), class: 'btn btn-floating btn-success btn-sm btn-edit' do %>
            <i class="far fa-edit"></i>
          <% end %>
        </span>
        <span>
          <%= link_to post_comment_path(comment.post, comment), class: 'btn btn-floating btn-danger btn-sm btn-delete', data: { turbo_method: :delete, turbo_confirm: '削除します' } do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </span>
      </div>
    <% end %>
    </div>
  </div>
  <hr>
<% end %>

app/views/posts/comments/_form.html.erb
<%= form_with(model: [post, comment], id: dom_id(comment, 'form'), class: 'row gy-2 gx-3 align-items-center') do |f| %>
  <%= render 'shared/error_messages', object: comment %>

  <div class="col-9">
    <div class="form-outline">
      <%= f.text_area :body, class: 'form-control' %>
      <%= f.label :body, class: 'form-label' %>
    </div>
  </div>

  <div class="col-3">
    <%= f.submit class: 'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/posts/comments/create.turbo_stream.erb
<% if @comment.valid? %>
  <%= turbo_stream.append "comments", @comment %>
<% end %>
<%= turbo_stream.replace(
      'form_comment',
      partial: 'form',
      locals: { post: @comment.post, comment: @comment.valid? ? Comment.new : @comment }
    ) %>

app/views/posts/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove(@comment) %>

app/views/posts/comments/edit.html.erb
<%= turbo_frame_tag dom_id @comment do %>
  <%= render 'form', post: @comment.post, comment: @comment %>
  <div class="mt-3">
    <%= link_to 'キャンセル', [@comment.post, @comment], class: 'btn btn-link btn-sm' %>
  </div>
  <hr>
<% end %>

app/views/posts/comments/show.html.erb
<%= render @comment %>

app/views/posts/comments/update.turbo_stream.erb
<% if @comment.valid? %>
  <%= turbo_stream.replace(@comment) %>
<% else %>
  <%= turbo_stream.replace(
        dom_id(@comment, 'form'),
        partial: 'form',
        locals: { post: @comment.post, comment: @comment }
      ) %>
<% end %>

app/views/posts/edit.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-xl-5 col-md-8">
      <div class="card">
        <div class="card-header">編集</div>
        <div class="card-body">
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-12">
      <%= render @posts %>
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>

<div class="position-fixed" style="right: 40px; bottom: 40px;">
  <%= link_to new_post_path, class: 'btn btn-floating btn-primary btn-lg' do %>
    <i class="fas fa-pencil-alt"></i>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-xl-5 col-md-8">
      <div class="card">
        <div class="card-header">新規作成</div>
        <div class="card-body">
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container card mt-3 p-0">
  <div class="row g-0">
    <div class="col-8">
      <%= render 'carousel_images', post: @post %>
    </div>
    <div class="col-4 d-flex flex-column justify-content-between">
      <div class="card-header">
        <div class="d-flex justify-content-between align-items-center">
          <div class="d-flex align-items-center gap-3">
            <%= image_tag 'http://placehold.jp/40x40.png',
                          class: 'rounded-circle',
                          width: 40,
                          height: 40 %>
            <span class="font-weight-bold"><%= @post.user.username %></span>
          </div>
          <!-- Menu -->
          <% if current_user && current_user.owner?(@post) %>
            <div class="dropdown text-center">
              <a
                class="text-reset me-3 dropdown-toggle hidden-arrow w-100 d-block"
                href="#"
                id="postDropdownMenuLink"
                role="button"
                data-mdb-toggle="dropdown"
                aria-expanded="false">
                <i class="fas fa-ellipsis-v"></i>
              </a>
              <ul
                class="dropdown-menu dropdown-menu-end"
                aria-labelledby="postDropdownMenuLink">
                <li>
                  <%= link_to '編集', edit_post_path(@post), class: 'dropdown-item' %>
                </li>
                <li>
                  <%= link_to '削除',
                              post_path(@post),
                              class: 'dropdown-item text-danger',
                              data: { turbo_method: :delete, turbo_confirm: '削除します' } %>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
      <div class="card-body" style="max-height: 400px; overflow-y: scroll">
        <div class="d-flex gap-3">
          <%= image_tag 'http://placehold.jp/40x40.png',
                        class: 'rounded-circle',
                        width: 40,
                        height: 40 %>
          <div class="w-100">
            <span class="font-weight-bold"><%= @post.user.username %></span>
            <%= simple_format(@post.body) %>
            <p class="card-text text-end">
              <small class="text-muted"><%= l @post.created_at, format: :long %></small>
            </p>
          </div>
        </div>
        <hr>

        <div id="comments">
          <%= render partial: 'posts/comments/comment', collection: @comments %>
        </div>
      </div>
      <div class="card-footer">
        <%= render 'posts/comments/form', post: @post, comment: @comment %>
      </div>
    </div>
  </div>

</div>

app/views/samples/index.html.erb
テストです

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul class="alert alert-danger">
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert-<%= message_type %> alert alert-dismissible fade show mb-3">
    <%= message %>
    <button type="button" class="btn-close" data-mdb-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<div style="height: calc(100vh - 58.59px); min-height: 400px;" class="d-flex align-items-center">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-5 col-md-8">
        <%= form_with url: login_path, class: 'bg-white  rounded-5 shadow-5-strong p-5', id: 'login-form' do |f| %>
          <div class="form-outline mb-4">
            <%= f.email_field :email, class: 'form-control' %>
            <%= f.label :email, User.human_attribute_name(:email), class: 'form-label' %>
          </div>
          <div class="form-outline mb-4">
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label :password, User.human_attribute_name(:password), class: 'form-label' %>
          </div>
          <%= f.submit 'ログイン', class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div style="height: calc(100vh - 58.59px); min-height: 400px;" class="d-flex align-items-center">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-5 col-md-8">
        <%= form_with model: @user, url: signup_path, class: 'bg-white  rounded-5 shadow-5-strong p-5' do |f| %>
          <%= render 'shared/error_messages', object: @user %>
          <div class="form-outline mb-4">
            <%= f.email_field :email, class: 'form-control' %>
            <%= f.label :email, class: 'form-label' %>
          </div>
          <div class="form-outline mb-4">
            <%= f.text_field :username, class: 'form-control' %>
            <%= f.label :username, class: 'form-label' %>
          </div>
          <div class="form-outline mb-4">
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label :password, class: 'form-label' %>
          </div>
          <div class="form-outline mb-4">
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            <%= f.label :password_confirmation, class: 'form-label' %>
          </div>
          <%= f.submit class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>